TECHNOLOGY('logistic-system'):remove_pack('high-tech-science-pack'):remove_pack('production-science-pack'):remove_pack('science-pack-3'):remove_prereq('advanced-electronics')
RECIPE('logistic-chest-storage'):remove_ingredient('advanced-circuit')
RECIPE('logistic-chest-passive-provider'):remove_ingredient('advanced-circuit')
RECIPE('logistic-chest-active-provider'):remove_ingredient('advanced-circuit')
RECIPE('logistic-chest-buffer'):remove_ingredient('advanced-circuit')
RECIPE('logistic-chest-requester'):remove_ingredient('advanced-circuit')
